luminance = lum80

<<include etc/housekeeping.conf>> 
<<include etc/colors_fonts_patterns.conf>> 
<<include samplecolor.conf>>


<<include image.conf>>
<<include ideogram.conf>>

<colors>
# r,g,b,a color definition
#
# a = 0 fully opaque
# a = 1 fully transparent
blackweak = 0,0,0,0.4
</colors>

karyotype = karyotype.txt
chromosomes_color = hs1=rp,hs2=rp,hs3=rp,hs4=rp,hs5=rd,hs6=rd,hs7=rd,hs8=rd,hs9=rd,hs10=sr,hs11=sr,hs12=sr,hs13=as,hs14=as,hs15=as,hs16=rpsr,hs17=rpsr,hs18=rpsr,hs19=rpsr,hs20=rpsr,hs21=rpsr,hs22=rpsr,hs23=rpsr,hs24=rpsr,hs25=rpsr,hs26=rprd,hs27=rprd,hs28=rpas,hs29=rpas,hs30=rpsras,hs31=rpsras,hs32=rpsras,hs33=rpsras,hs34=rpsrrd,hs35=rpsrrd,hs36=rpsrrd,hs37=rpsrrd,hs38=rpsrrd,hs39=otr,hs40=otr

<<include hist.conf>>

